# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActiveStorage::Current < ::ActiveSupport::CurrentAttributes
  def host=: (untyped host) -> untyped
  def host: () -> untyped
end
