# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActiveStorage::Record < ::ActiveRecord::Base
  include ActiveStorage::Record::GeneratedAttributeMethods
  include ActiveStorage::Record::GeneratedAssociationMethods
end
