# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActionController::RespondToMismatchError < ::ActionController::ActionControllerError
  def initialize: (?untyped? message) -> void
  DEFAULT_MESSAGE: String
end
