# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActionController::UnpermittedParameters < ::IndexError
  def initialize: (untyped params) -> void
  attr_reader params: untyped
end
