# !!! GENERATED CODE !!!
# Please see generators/rails-generator

module ActionDispatch::TestProcess::FixtureFile
  # Shortcut for <tt>Rack::Test::UploadedFile.new(File.join(ActionDispatch::IntegrationTest.file_fixture_path, path), type)</tt>:
  #
  #   post :change_avatar, params: { avatar: fixture_file_upload('david.png', 'image/png') }
  #
  # Default fixture files location is <tt>test/fixtures/files</tt>.
  #
  # To upload binary files on Windows, pass <tt>:binary</tt> as the last parameter.
  # This will not affect other platforms:
  #
  #   post :change_avatar, params: { avatar: fixture_file_upload('david.png', 'image/png', :binary) }
  def fixture_file_upload: (untyped path, ?untyped? mime_type, ?bool binary) -> untyped
end
