# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActionView::CacheExpiry::ViewModificationWatcher
  def initialize: (watcher: untyped) ?{ () -> untyped } -> void
  def execute_if_updated: () -> untyped
  private def dirs_to_watch: () -> untyped
  private def all_view_paths: () -> untyped
end
