# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class Arel::Visitors::Dot::Node
  def initialize: (untyped name, untyped id, ?untyped fields) -> void
  attr_accessor name: untyped
  attr_accessor id: untyped
  attr_accessor fields: untyped
end
