# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActionDispatch::Journey::Format
  def self.required_path: (untyped symbol) -> untyped
  def self.required_segment: (untyped symbol) -> untyped
  def initialize: (untyped parts) -> void
  def evaluate: (untyped hash) -> ("" | untyped)
  ESCAPE_PATH: Proc
  ESCAPE_SEGMENT: Proc
end
