# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class Arel::Nodes::Case < ::Arel::Nodes::Node
  include Arel::OrderPredications
  include Arel::Predications
  include Arel::AliasPredication
  attr_accessor case: untyped
  attr_accessor conditions: untyped
  attr_accessor default: untyped
end
