# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class Arel::Nodes::Extract < ::Arel::Nodes::Unary
  include Arel::AliasPredication
  include Arel::Predications
  attr_accessor field: untyped
end
