# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class Arel::Nodes::SelectStatement < ::Arel::Nodes::Node
  attr_accessor limit: untyped
  attr_accessor orders: untyped
  attr_accessor lock: untyped
  attr_accessor offset: untyped
  attr_accessor with: untyped
  attr_reader cores: untyped
end
