# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class Arel::Nodes::SqlLiteral < ::String
  include Arel::Expressions
  include Arel::Predications
  include Arel::AliasPredication
  include Arel::OrderPredications
end
