# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class Arel::Nodes::UnaryOperation < ::Arel::Nodes::Unary
  include Arel::Expressions
  include Arel::Predications
  include Arel::OrderPredications
  include Arel::AliasPredication
  include Arel::Math
  attr_reader operator: untyped
end
