# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActionView::Template::Handlers::LegacyHandlerWrapper < SimpleDelegator
  def call: (untyped view, untyped source) -> untyped
end
