# !!! GENERATED CODE !!!
# Please see generators/rails-generator

module ActiveRecord::Transactions::ClassMethods
  # See the ConnectionAdapters::DatabaseStatements#transaction API docs.
  def transaction: (**untyped options) ?{ () -> untyped } -> untyped
  def before_commit: (*untyped args) ?{ () -> untyped } -> untyped
  # This callback is called after a record has been created, updated, or destroyed.
  #
  # You can specify that the callback should only be fired by a certain action with
  # the +:on+ option:
  #
  #   after_commit :do_foo, on: :create
  #   after_commit :do_bar, on: :update
  #   after_commit :do_baz, on: :destroy
  #
  #   after_commit :do_foo_bar, on: [:create, :update]
  #   after_commit :do_bar_baz, on: [:update, :destroy]
  #
  def after_commit: (*untyped args) ?{ () -> untyped } -> untyped
  # Shortcut for <tt>after_commit :hook, on: [ :create, :update ]</tt>.
  def after_save_commit: (*untyped args) ?{ () -> untyped } -> untyped
  # Shortcut for <tt>after_commit :hook, on: :create</tt>.
  def after_create_commit: (*untyped args) ?{ () -> untyped } -> untyped
  # Shortcut for <tt>after_commit :hook, on: :update</tt>.
  def after_update_commit: (*untyped args) ?{ () -> untyped } -> untyped
  # Shortcut for <tt>after_commit :hook, on: :destroy</tt>.
  def after_destroy_commit: (*untyped args) ?{ () -> untyped } -> untyped
  # This callback is called after a create, update, or destroy are rolled back.
  #
  # Please check the documentation of #after_commit for options.
  def after_rollback: (*untyped args) ?{ () -> untyped } -> untyped
  def before_commit_without_transaction_enrollment: (*untyped args) ?{ () -> untyped } -> untyped
  def after_commit_without_transaction_enrollment: (*untyped args) ?{ () -> untyped } -> untyped
  def after_rollback_without_transaction_enrollment: (*untyped args) ?{ () -> untyped } -> untyped
  private def set_options_for_callbacks!: (untyped args, ?::Hash[untyped, untyped] enforced_options) -> untyped
  private def assert_valid_transaction_action: (untyped actions) -> (untyped | nil)
end
