# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActionController::MiddlewareStack::Middleware < ::ActionDispatch::MiddlewareStack::Middleware
  def initialize: (untyped klass, untyped args, untyped actions, untyped strategy, untyped block) -> void
  def valid?: (untyped action) -> untyped
end
