# !!! GENERATED CODE !!!
# Please see generators/rails-generator

module ActiveRecord::ReadonlyAttributes::ClassMethods
  # Attributes listed as readonly will be used to create a new record but update operations will
  # ignore these fields.
  #
  # You can assign a new value to a readonly attribute, but it will be ignored when the record is updated.
  #
  # ==== Examples
  #
  #   class Post < ActiveRecord::Base
  #     attr_readonly :title
  #   end
  #
  #   post = Post.create!(title: "Introducing Ruby on Rails!")
  #   post.update(title: "a different title") # change to title will be ignored
  def attr_readonly: (*untyped attributes) -> untyped
  # Returns an array of all the attributes that have been specified as readonly.
  def readonly_attributes: () -> untyped
  def readonly_attribute?: (untyped name) -> untyped
end
