# !!! GENERATED CODE !!!
# Please see generators/rails-generator

module ActiveRecord::Timestamp::ClassMethods
  def touch_attributes_with_time: (*untyped names, ?time: untyped?) -> untyped
  def timestamp_attributes_for_create_in_model: () -> untyped
  def timestamp_attributes_for_update_in_model: () -> untyped
  def all_timestamp_attributes_in_model: () -> untyped
  def current_time_from_proper_timezone: () -> untyped
  private def timestamp_attributes_for_create: () -> untyped
  private def timestamp_attributes_for_update: () -> untyped
  private def reload_schema_from_cache: () -> untyped
end
