# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActionView::MissingTemplate < ::ActionView::ActionViewError
  def initialize: (untyped paths, untyped path, untyped prefixes, untyped partial, untyped details) -> void
  attr_reader path: untyped
end
