# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActionView::UnboundTemplate
  def initialize: (untyped source, untyped identifer, untyped handler, untyped options) -> void
  def bind_locals: (untyped locals) -> untyped
  private def build_template: (untyped locals) -> untyped
end
