# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActiveRecord::Store::HashAccessor
  def self.read: (untyped object, untyped attribute, untyped key) -> untyped
  def self.write: (untyped object, untyped attribute, untyped key, untyped value) -> untyped
  def self.prepare: (untyped object, untyped attribute) -> (untyped | nil)
end
