# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class Arel::Collectors::SubstituteBinds
  def initialize: (untyped quoter, untyped delegate_collector) -> void
  def <<: (untyped str) -> self
  def add_bind: (untyped bind) -> untyped
  def value: () -> untyped
  attr_reader quoter: untyped
  attr_reader delegate: untyped
end
