# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class Arel::Nodes::Regexp < ::Arel::Nodes::Binary
  def initialize: (untyped left, untyped right, ?bool case_sensitive) -> void
  attr_accessor case_sensitive: untyped
end
