# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class Arel::Nodes::SqlLiteral < ::String
  def encode_with: (untyped coder) -> untyped
  include Arel::Expressions
  include Arel::Predications
  include Arel::AliasPredication
  include Arel::OrderPredications
end
