# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActiveRecord::DatabaseConfigurations::HashConfig < ::ActiveRecord::DatabaseConfigurations::DatabaseConfig
  def initialize: (untyped env_name, untyped name, untyped configuration_hash) -> void
  # Determines whether a database configuration is for a replica / readonly
  # connection. If the +replica+ key is present in the config, +replica?+ will
  # return +true+.
  def replica?: () -> untyped
  # The migrations paths for a database configuration. If the
  # +migrations_paths+ key is present in the config, +migrations_paths+
  # will return its value.
  def migrations_paths: () -> untyped
  def host: () -> untyped
  def socket: () -> untyped
  def database: () -> untyped
  def _database=: (untyped database) -> untyped
  def pool: () -> untyped
  def min_threads: () -> untyped
  def max_threads: () -> untyped
  def max_queue: () -> untyped
  def checkout_timeout: () -> untyped
  # +reaping_frequency+ is configurable mostly for historical reasons, but it could
  # also be useful if someone wants a very low +idle_timeout+.
  def reaping_frequency: () -> untyped
  def idle_timeout: () -> untyped
  def adapter: () -> untyped
  # The path to the schema cache dump file for a database.
  # If omitted, the filename will be read from ENV or a
  # default will be derived.
  def schema_cache_path: () -> untyped
  def default_schema_cache_path: () -> "db/schema_cache.yml"
  def lazy_schema_cache_path: () -> untyped
  def primary?: () -> untyped
  # Determines whether to dump the schema/structure files and the
  # filename that should be used.
  #
  # If +configuration_hash[:schema_dump]+ is set to +false+ or +nil+
  # the schema will not be dumped.
  #
  # If the config option is set that will be used. Otherwise Rails
  # will generate the filename from the database config name.
  def schema_dump: (?untyped format) -> (untyped | nil | untyped | ::String)
  def database_tasks?: () -> untyped
  private def schema_file_type: (untyped format) -> untyped
  attr_reader configuration_hash: untyped
end
