# !!! GENERATED CODE !!!
# Please see generators/rails-generator

module ActiveRecord::CounterCache
  private def _create_record: () -> untyped

  private def destroy_row: () -> untyped

  private def each_counter_cached_associations: () { (untyped) -> untyped } -> untyped

  extend ActiveSupport::Concern
end
