# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActiveRecord::ExplainRegistry
  def initialize: () -> void
  def collect?: () -> untyped
  def reset: () -> untyped
  extend ActiveSupport::PerThreadRegistry
  attr_accessor queries: untyped
  attr_accessor collect: untyped
end
