# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActiveRecord::MigrationContext
  def initialize: (untyped migrations_paths) -> void
  def migrate: (?untyped? target_version) ?{ () -> untyped } -> untyped
  def rollback: (?::Integer steps) -> untyped
  def forward: (?::Integer steps) -> untyped
  def up: (?untyped? target_version) { (untyped) -> untyped } -> untyped
  def down: (?untyped? target_version) { (untyped) -> untyped } -> untyped
  def run: (untyped direction, untyped target_version) -> untyped
  def open: () -> untyped
  def get_all_versions: () -> (untyped | ::Array[untyped])
  def current_version: () -> untyped
  def needs_migration?: () -> untyped
  def any_migrations?: () -> untyped
  def last_migration: () -> untyped
  def parse_migration_filename: (untyped filename) -> untyped
  def migrations: () -> untyped
  def migrations_status: () -> untyped
  def migration_files: () -> untyped
  def current_environment: () -> untyped
  def protected_environment?: () -> (untyped | nil)
  def last_stored_environment: () -> (nil | untyped)
  private def move: (untyped direction, untyped steps) -> untyped
  attr_reader migrations_paths: untyped
end
