# !!! GENERATED CODE !!!
# Please see generators/rails-generator

module ActiveRecord::NoTouching
  def self.apply_to: (untyped klass) { () -> untyped } -> untyped

  def self.applied_to?: (untyped klass) -> untyped

  private def self.klasses: () -> untyped

  def no_touching?: () -> untyped

  def touch_later: () -> (untyped | nil)

  def touch: () -> (untyped | nil)

  extend ActiveSupport::Concern
end
