# !!! GENERATED CODE !!!
# Please see generators/rails-generator

module ActiveRecord::Reflection
  def self.create: (untyped macro, untyped name, untyped scope, untyped options, untyped ar) -> untyped

  def self.add_reflection: (untyped ar, untyped name, untyped reflection) -> untyped

  def self.add_aggregate_reflection: (untyped ar, untyped name, untyped reflection) -> untyped

  extend ActiveSupport::Concern
end
