# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActiveRecord::SuppressorRegistry
  def initialize: () -> void
  extend ActiveSupport::PerThreadRegistry
  attr_reader suppressed: untyped
end
