# !!! GENERATED CODE !!!
# Please see generators/rails-generator

module Digest::UUID
  # Generates a v5 non-random UUID (Universally Unique IDentifier).
  #
  # Using OpenSSL::Digest::MD5 generates version 3 UUIDs; OpenSSL::Digest::SHA1 generates version 5 UUIDs.
  # uuid_from_hash always generates the same UUID for a given name and namespace combination.
  #
  # See RFC 4122 for details of UUID at: https://www.ietf.org/rfc/rfc4122.txt
  def self.uuid_from_hash: (untyped hash_class, untyped namespace, untyped name) -> untyped
  # Convenience method for uuid_from_hash using OpenSSL::Digest::MD5.
  def self.uuid_v3: (untyped uuid_namespace, untyped name) -> untyped
  # Convenience method for uuid_from_hash using OpenSSL::Digest::SHA1.
  def self.uuid_v5: (untyped uuid_namespace, untyped name) -> untyped
  # Convenience method for SecureRandom.uuid.
  def self.uuid_v4: () -> untyped
  def self.pack_uuid_namespace: (untyped namespace) -> untyped
  def self.use_rfc4122_namespaced_uuids: () -> untyped
  def self.use_rfc4122_namespaced_uuids=: (untyped val) -> untyped
  DNS_NAMESPACE: String
  OID_NAMESPACE: String
  URL_NAMESPACE: String
  X500_NAMESPACE: String
end
