# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class Arel::TreeManager
  def to_dot: () -> untyped
  def to_sql: (?untyped engine) -> untyped
  def initialize_copy: (untyped other) -> untyped
  include Arel::FactoryMethods
  attr_reader ast: untyped
end
