# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActiveSupport::EnvironmentInquirer < ::ActiveSupport::StringInquirer
  def initialize: (untyped env) -> void
  DEFAULT_ENVIRONMENTS: Array[String]
end
