# !!! GENERATED CODE !!!
# Please see generators/rails-generator

module ActiveSupport::LoggerThreadSafeLevel
  def local_level: () -> untyped
  def local_level=: (untyped level) -> untyped
  def level: () -> untyped
  # Change the thread-local level for the duration of the given block.
  def log_at: (untyped level) { () -> untyped } -> untyped
  # Redefined to check severity against #level, and thus the thread-local level, rather than +@level+.
  # FIXME: Remove when the minimum Ruby version supports overriding Logger#level.
  def add: (untyped severity, ?untyped? message, ?untyped? progname) { () -> untyped } -> (true | untyped)
  extend ActiveSupport::Concern
end
