# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActiveSupport::Testing::Parallelization::Server
  def initialize: () -> void
  def record: (untyped reporter, untyped result) -> untyped
  def <<: (untyped o) -> untyped
  def length: () -> untyped
  def pop: () -> untyped
  include DRb::DRbUndumped
end
