# !!! GENERATED CODE !!!
# Please see generators/rails-generator

D = Steep::Diagnostic

target :test do
  signature "."
  check "."

  repo_path "../../../"

  library "time"
  library "monitor"
  library "singleton"
  library "logger"
  library "mutex_m"
  library "json"
  library "date"
  library "benchmark"
  library "digest"
  library "minitest"
  library "nokogiri"

  library "activejob:7.0"
  library "activesupport:7.0"

  configure_code_diagnostics(D::Ruby.all_error)
end
