# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActiveJob::QueueAdapters::SidekiqAdapter
  def enqueue: (untyped job) -> untyped
  def enqueue_at: (untyped job, untyped timestamp) -> untyped
end
