# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActionDispatch::Journey::Visitors::FormatBuilder < ::ActionDispatch::Journey::Visitors::Visitor
  def accept: (untyped node) -> untyped
  def terminal: (untyped node) -> ::Array[untyped]
  def binary: (untyped node) -> untyped
  def visit_GROUP: (untyped n) -> ::Array[untyped]
  def visit_STAR: (untyped n) -> ::Array[untyped]
  def visit_SYMBOL: (untyped n) -> untyped
end
