# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActiveModel::Validations::ComparisonValidator < ::ActiveModel::EachValidator
  def check_validity!: () -> (untyped | nil)
  def validate_each: (untyped record, untyped attr_name, untyped value) -> untyped
  include ActiveModel::Validations::Comparability
end
