# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class AbstractController::DoubleRenderError < ::AbstractController::Error
  def initialize: (?untyped? message) -> void
  DEFAULT_MESSAGE: String
end
