# !!! GENERATED CODE !!!
# Please see generators/rails-generator

module AbstractController::UrlFor
  def _routes: () -> untyped
  include ActionDispatch::Routing::UrlFor
  extend ActiveSupport::Concern
end
