# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActiveRecord::Encryption::ExtendedDeterministicQueries::AdditionalValue
  def initialize: (untyped value, untyped `type`) -> void
  private def process: (untyped value) -> untyped
  attr_reader value: untyped
  attr_reader type: untyped
end
