# !!! GENERATED CODE !!!
# Please see generators/rails-generator

module ActiveRecord::Encryption::ExtendedDeterministicQueries::CoreQueries
  def find_by: (*untyped args) -> untyped
  extend ActiveSupport::Concern
end
