# !!! GENERATED CODE !!!
# Please see generators/rails-generator

module ActiveRecord::Encryption::ExtendedDeterministicQueries::ExtendedEncryptableType
  def serialize: (untyped data) -> untyped
end
