# !!! GENERATED CODE !!!
# Please see generators/rails-generator

module Mime
  def self.[]: (untyped `type`) -> untyped
  def self.fetch: (untyped `type`) ?{ () -> untyped } -> untyped
  ALL: Mime::AllType
  EXTENSION_LOOKUP: Hash[String, Mime::Type]
  LOOKUP: Hash[String, Mime::Type]
  SET: Mime::Mimes
end
