# !!! GENERATED CODE !!!
# Please see generators/rails-generator

module ActiveStorage::SetHeaders
  private def set_content_headers_from: (untyped blob) -> untyped
  extend ActiveSupport::Concern
end
