# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActiveJob::QueueAdapters::QuAdapter::JobWrapper < Qu::Job
  def initialize: (untyped job_data) -> void
  def perform: () -> untyped
end
