# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActiveSupport::Notifications::Fanout
  def initialize: () -> void
  def subscribe: (?untyped? pattern, ?untyped? callable) ?{ () -> untyped } -> untyped
  def unsubscribe: (untyped subscriber_or_name) -> untyped
  def start: (untyped name, untyped id, untyped payload) -> untyped
  def finish: (untyped name, untyped id, untyped payload, ?untyped listeners) -> untyped
  def publish: (untyped name, *untyped args) -> untyped
  def listeners_for: (untyped name) -> untyped
  def listening?: (untyped name) -> untyped
  # This is a sync queue, so there is no waiting.
  def wait: () -> nil
  include Mutex_m
end
