# !!! GENERATED CODE !!!
# Please see generators/rails-generator

module ActionDispatch::Routing::Mapper::HttpHelpers
  # Define a route that only recognizes HTTP GET.
  # For supported arguments, see match[rdoc-ref:Base#match]
  #
  #   get 'bacon', to: 'food#bacon'
  def get: (*untyped args) ?{ () -> untyped } -> untyped
  # Define a route that only recognizes HTTP POST.
  # For supported arguments, see match[rdoc-ref:Base#match]
  #
  #   post 'bacon', to: 'food#bacon'
  def post: (*untyped args) ?{ () -> untyped } -> untyped
  # Define a route that only recognizes HTTP PATCH.
  # For supported arguments, see match[rdoc-ref:Base#match]
  #
  #   patch 'bacon', to: 'food#bacon'
  def patch: (*untyped args) ?{ () -> untyped } -> untyped
  # Define a route that only recognizes HTTP PUT.
  # For supported arguments, see match[rdoc-ref:Base#match]
  #
  #   put 'bacon', to: 'food#bacon'
  def put: (*untyped args) ?{ () -> untyped } -> untyped
  # Define a route that only recognizes HTTP DELETE.
  # For supported arguments, see match[rdoc-ref:Base#match]
  #
  #   delete 'broccoli', to: 'food#broccoli'
  def delete: (*untyped args) ?{ () -> untyped } -> untyped
  # Define a route that only recognizes HTTP OPTIONS.
  # For supported arguments, see match[rdoc-ref:Base#match]
  #
  #   options 'carrots', to: 'food#carrots'
  def options: (*untyped args) ?{ () -> untyped } -> untyped
  private def map_method: (untyped method, untyped args) ?{ () -> untyped } -> self
end
