# !!! GENERATED CODE !!!
# Please see generators/rails-generator

module ActionController::Caching
  private def instrument_payload: (untyped key) -> { controller: untyped, action: untyped, key: untyped }
  private def instrument_name: () -> "action_controller"
  extend ActiveSupport::Concern
end
