# !!! GENERATED CODE !!!
# Please see generators/rails-generator

module ActionController::Rendering
  # Before processing, set the request formats in current controller formats.
  def process_action: () -> untyped
  # Check for double render errors and set the content_type after rendering.
  def render: (*untyped args) -> untyped
  # Overwrite render_to_string because body can now be set to a Rack body.
  def render_to_string: () -> untyped
  def render_to_body: (?::Hash[untyped, untyped] options) -> untyped
  private def _process_variant: (untyped options) -> (untyped | nil)
  private def _render_in_priorities: (untyped options) -> (untyped | nil)
  private def _set_html_content_type: () -> untyped
  private def _set_rendered_content_type: (untyped format) -> (untyped | nil)
  private def _set_vary_header: () -> (untyped | nil)
  # Normalize arguments by catching blocks and setting them on :update.
  private def _normalize_args: (?untyped? action, ?::Hash[untyped, untyped] options) ?{ () -> untyped } -> untyped
  # Normalize both text and status options.
  private def _normalize_options: (untyped options) -> untyped
  private def _normalize_text: (untyped options) -> untyped
  # Process controller specific options, as status, content-type and location.
  private def _process_options: (untyped options) -> untyped
  extend ActiveSupport::Concern
  RENDER_FORMATS_IN_PRIORITY: Array[Symbol]
end
