# !!! GENERATED CODE !!!
# Please see generators/rails-generator

module ActionController::ApiRendering
  def render_to_body: (?::Hash[untyped, untyped] options) -> untyped
  extend ActiveSupport::Concern
end
