# !!! GENERATED CODE !!!
# Please see generators/rails-generator

module ActionController::BasicImplicitRender
  def send_action: (untyped method, *untyped args) -> untyped
  def default_render: () -> untyped
end
