# !!! GENERATED CODE !!!
# Please see generators/rails-generator

module ActionController::ContentSecurityPolicy
  private def content_security_policy?: () -> untyped
  private def content_security_policy_nonce: () -> untyped
  private def current_content_security_policy: () -> untyped
  include AbstractController::Helpers
  include AbstractController::Callbacks
  extend ActiveSupport::Concern
end
