# !!! GENERATED CODE !!!
# Please see generators/rails-generator

module ActionController::EtagWithTemplateDigest
  private def determine_template_etag: (untyped options) -> (untyped | nil)
  # Pick the template digest to include in the ETag. If the +:template+ option
  # is present, use the named template. If +:template+ is +nil+ or absent, use
  # the default controller/action template. If +:template+ is false, omit the
  # template digest from the ETag.
  private def pick_template_for_etag: (untyped options) -> (untyped | nil)
  private def lookup_and_digest_template: (untyped template) -> untyped
  include ActionController::ConditionalGet
  extend ActiveSupport::Concern
end
