# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActionController::LiveTestResponse < ::ActionController::Live::Response
  # Was the response successful?
  alias success? successful?
  # Was the URL not found?
  alias missing? not_found?
  # Was there a server-side error?
  alias error? server_error?
end
