# !!! GENERATED CODE !!!
# Please see generators/rails-generator

module ActionController::StrongParameters
  # Returns a new ActionController::Parameters object that
  # has been instantiated with the <tt>request.parameters</tt>.
  def params: () -> untyped
  # Assigns the given +value+ to the +params+ hash. If +value+
  # is a Hash, this will create an ActionController::Parameters
  # object that has been instantiated with the given +value+ hash.
  def params=: (untyped value) -> untyped
end
