# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActionDispatch::Cookies::MarshalWithJsonFallback
  def self.load: (untyped value) -> untyped
  def self.dump: (untyped value) -> untyped
end
