# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActiveStorage::Attachment::ActiveRecord_AssociationRelation < ::ActiveRecord::AssociationRelation
  include ActiveRecord::Delegation::ClassSpecificRelation
  include ActiveStorage::Attachment::GeneratedRelationMethods
  extend ActiveRecord::Delegation::ClassSpecificRelation::ClassMethods
end
