# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class Arel::Nodes::UnaryOperation < ::Arel::Nodes::Unary
  def initialize: (untyped operator, untyped operand) -> void
  attr_reader operator: untyped
end
