# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActionDispatch::Routing::RouteSet::NamedRouteCollection::UrlHelper
  def self.create: (untyped route, untyped options, untyped route_name) -> untyped
  def self.optimize_helper?: (untyped route) -> untyped
  def initialize: (untyped route, untyped options, untyped route_name) -> void
  def call: (untyped t, untyped method_name, untyped args, untyped inner_options, untyped url_strategy) -> untyped
  def handle_positional_args: (untyped controller_options, untyped inner_options, untyped args, untyped result, untyped path_params) -> untyped
  attr_reader route_name: untyped
end
