# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActionDispatch::Routing::Mapper
  # Invokes Journey::Router::Utils.normalize_path and ensure that
  # (:locale) becomes (/:locale) instead of /(:locale). Except
  # for root cases, where the latter is the correct one.
  def self.normalize_path: (untyped path) -> untyped
  def self.normalize_name: (untyped name) -> untyped
  def initialize: (untyped set) -> void
  include ActionDispatch::Routing::Mapper::Base
  include ActionDispatch::Routing::Mapper::HttpHelpers
  include ActionDispatch::Routing::Redirection
  include ActionDispatch::Routing::Mapper::Scoping
  include ActionDispatch::Routing::Mapper::Concerns
  include ActionDispatch::Routing::Mapper::Resources
  include ActionDispatch::Routing::Mapper::CustomUrls
  URL_OPTIONS: Array[Symbol]
end
