# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActiveRecord::AsynchronousQueriesTracker::Session
  def initialize: () -> void
  def active?: () -> untyped
  def finalize: () -> untyped
end
