# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActiveSupport::Notifications::Fanout::Subscribers::Evented
  def initialize: (untyped pattern, untyped delegate) -> void
  def publish: (untyped name, *untyped args) -> (untyped | nil)
  def publish_event: (untyped event) -> untyped
  def start: (untyped name, untyped id, untyped payload) -> untyped
  def finish: (untyped name, untyped id, untyped payload) -> untyped
  def subscribed_to?: (untyped name) -> untyped
  def unsubscribe!: (untyped name) -> untyped
  attr_reader pattern: untyped
end
