# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActionDispatch::Journey::Nodes::Group < ::ActionDispatch::Journey::Nodes::Unary
  def type: () -> :GROUP
  def group?: () -> true
end
