# !!! GENERATED CODE !!!
# Please see generators/rails-generator

module ActionView
  # Returns the version of the currently loaded Action View as a <tt>Gem::Version</tt>
  def self.gem_version: () -> untyped
  # Returns the version of the currently loaded ActionView as a <tt>Gem::Version</tt>
  def self.version: () -> untyped
  def self.eager_load!: () -> untyped
  extend ActiveSupport::Autoload
  ENCODING_FLAG: String
end
