# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class Arel::SelectManager < ::Arel::TreeManager
  include Arel::Crud
  STRING_OR_SYMBOL_CLASS: Array[singleton(Symbol) | singleton(String)]
end
