# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActiveSupport::LegacyKeyGenerator
  def initialize: (untyped secret) -> void
  def generate_key: (untyped salt) -> untyped
  # To prevent users from using something insecure like "Password" we make sure that the
  # secret they've provided is at least 30 characters in length.
  private def ensure_secret_secure: (untyped secret) -> untyped
  SECRET_MIN_LENGTH: Integer
end
