# !!! GENERATED CODE !!!
# Please see generators/rails-generator

module ActiveSupport::Multibyte
  # The proxy class returned when calling mb_chars. You can use this accessor
  # to configure your own proxy class so you can support other encodings. See
  # the ActiveSupport::Multibyte::Chars implementation for an example how to
  # do this.
  #
  #   ActiveSupport::Multibyte.proxy_class = CharsForUTF32
  def self.proxy_class=: (untyped klass) -> untyped

  # Returns the current proxy class.
  def self.proxy_class: () -> untyped
end
