# !!! GENERATED CODE !!!
# Please see generators/rails-generator

module ActiveSupport::Tryable : BasicObject
  def try: (*untyped a) ?{ () -> untyped } -> (untyped | nil)

  def try!: (*untyped a) { (untyped) -> untyped } -> untyped
end
