# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActiveModel::Attribute::FromDatabase < ::ActiveModel::Attribute
  def type_cast: (untyped value) -> untyped
  private def _original_value_for_database: () -> untyped
end
