# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class LoadError < ::ScriptError
  # Returns true if the given path name (except perhaps for the ".rb"
  # extension) is the missing file which caused the exception to be raised.
  def is_missing?: (untyped location) -> untyped
end
