# !!! GENERATED CODE !!!
# Please see generators/rails-generator

module ActiveRecord
  # Returns the currently loaded version of Active Record as a <tt>Gem::Version</tt>.
  def self.gem_version: () -> untyped
  # Returns the currently loaded version of Active Record as a <tt>Gem::Version</tt>.
  def self.version: () -> untyped
  # Determines whether to use Time.utc (using :utc) or Time.local (using :local) when pulling
  # dates and times from the database. This is set to :utc by default.
  def self.default_timezone=: (untyped default_timezone) -> untyped
  def self.global_thread_pool_async_query_executor: () -> untyped
  # Set the +global_executor_concurrency+. This configuration value can only be used
  # with the global thread pool async query executor.
  def self.global_executor_concurrency=: (untyped global_executor_concurrency) -> untyped
  def self.global_executor_concurrency: () -> untyped
  def self.eager_load!: () -> untyped
  extend ActiveSupport::Autoload
  attr_accessor self.lazily_load_schema_cache: untyped
  attr_accessor self.schema_cache_ignored_tables: untyped
  attr_accessor self.legacy_connection_handling: untyped
  attr_accessor self.writing_role: untyped
  attr_accessor self.reading_role: untyped
  attr_accessor self.async_query_executor: untyped
  attr_accessor self.index_nested_attribute_errors: untyped
  attr_accessor self.verbose_query_logs: untyped
  attr_accessor self.queues: untyped
  attr_accessor self.maintain_test_schema: untyped
  attr_accessor self.warn_on_records_fetched_greater_than: untyped
  attr_accessor self.application_record_class: untyped
  attr_accessor self.action_on_strict_loading_violation: untyped
  attr_accessor self.schema_format: untyped
  attr_accessor self.error_on_ignored_order: untyped
  attr_accessor self.timestamped_migrations: untyped
  attr_accessor self.dump_schema_after_migration: untyped
  attr_accessor self.dump_schemas: untyped
  attr_accessor self.suppress_multiple_database_warning: untyped
  attr_accessor self.verify_foreign_keys_for_fixtures: untyped
  attr_accessor self.query_transformers: untyped
  attr_accessor self.use_yaml_unsafe_load: untyped
  attr_accessor self.yaml_column_permitted_classes: untyped
  attr_reader self.default_timezone: untyped
end
