# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActiveModel::NestedError < ::ActiveModel::Error
  def initialize: (untyped base, untyped inner_error, ?::Hash[untyped, untyped] override_options) -> void
  extend Forwardable
  attr_reader inner_error: untyped
end
