# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActionDispatch::Cookies::PermanentCookieJar < ::ActionDispatch::Cookies::AbstractCookieJar
  private def commit: (untyped name, untyped options) -> untyped
end
