# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActionDispatch::Cookies::SignedKeyRotatingCookieJar < ::ActionDispatch::Cookies::AbstractCookieJar
  def initialize: (untyped parent_jar) -> void
  private def parse: (untyped name, untyped signed_message, ?purpose: untyped?) -> untyped
  private def commit: (untyped name, untyped options) -> untyped
  include ActionDispatch::Cookies::SerializedCookieJars
end
