# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActiveSupport::DescendantsTracker::WeakSet
  def initialize: () -> void
  def []: (untyped object) -> untyped
  def []=: (untyped object, untyped _present) -> untyped
end
