# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActiveSupport::Notifications::InstrumentationSubscriberError < ::RuntimeError
  def initialize: (untyped exceptions) -> void
  attr_reader exceptions: untyped
end
