# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActiveStorage::Attachment < ::ActiveRecord::Base
  # Synchronously deletes the attachment and {purges the blob}[rdoc-ref:ActiveStorage::Blob#purge].
  def purge: () -> untyped
  # Deletes the attachment and {enqueues a background job}[rdoc-ref:ActiveStorage::Blob#purge_later] to purge the blob.
  def purge_later: () -> untyped
  private def identify_blob: () -> untyped
  private def analyze_blob_later: () -> (untyped | nil)
  private def purge_dependent_blob_later: () -> (untyped | nil)
  private def dependent: () -> untyped
  include ActiveStorage::Attachment::GeneratedAttributeMethods
  include ActiveStorage::Attachment::GeneratedAssociationMethods
end
