# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActiveStorage::BaseController < ::ActionController::Base
  include ActionDispatch::Routing::UrlFor
  include ActiveStorage::SetCurrent
end
