# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActiveStorage::RepresentationsController < ::ActiveStorage::BaseController
  def show: () -> untyped
  include ActionDispatch::Routing::UrlFor
  include ActiveStorage::SetBlob
end
