# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActiveRecord::StatementCache::Query
  def initialize: (untyped sql) -> void
  def sql_for: (untyped binds, untyped connection) -> untyped
end
