# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class Arel::Nodes::Comment < ::Arel::Nodes::Node
  def initialize: (untyped values) -> void
  def initialize_copy: (untyped other) -> untyped
  def hash: () -> untyped
  def eql?: (untyped other) -> untyped
  alias == eql?
  attr_reader values: untyped
end
