# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class Arel::Nodes::In < ::Arel::Nodes::Binary
  def equality?: () -> true
  def invert: () -> untyped
  include Arel::Nodes::FetchAttribute
end
