# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class Arel::Nodes::InsertStatement < ::Arel::Nodes::Node
  def initialize: () -> void
  def initialize_copy: (untyped other) -> untyped
  def hash: () -> untyped
  def eql?: (untyped other) -> untyped
  alias == eql?
  attr_accessor relation: untyped
  attr_accessor columns: untyped
  attr_accessor values: untyped
  attr_accessor select: untyped
end
