# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class Arel::Nodes::Over < ::Arel::Nodes::Binary
  def initialize: (untyped left, ?untyped? right) -> void
  def operator: () -> "OVER"
  include Arel::AliasPredication
end
