# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActiveStorage::Representations::ProxyController < ::ActiveStorage::Representations::BaseController
  def show: () -> untyped
end
