# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class Arel::Visitors::DepthFirst < ::Arel::Visitors::Visitor
  def initialize: (?untyped? block) -> void
  private def visit: (untyped o, ?untyped? _) -> untyped
  private def unary: (untyped o) -> untyped
  alias visit_Arel_Nodes_Else unary
  alias visit_Arel_Nodes_Group unary
  alias visit_Arel_Nodes_Cube unary
  alias visit_Arel_Nodes_RollUp unary
  alias visit_Arel_Nodes_GroupingSet unary
  alias visit_Arel_Nodes_GroupingElement unary
  alias visit_Arel_Nodes_Grouping unary
  alias visit_Arel_Nodes_Having unary
  alias visit_Arel_Nodes_Lateral unary
  alias visit_Arel_Nodes_Limit unary
  alias visit_Arel_Nodes_Not unary
  alias visit_Arel_Nodes_Offset unary
  alias visit_Arel_Nodes_On unary
  alias visit_Arel_Nodes_Ordering unary
  alias visit_Arel_Nodes_Ascending unary
  alias visit_Arel_Nodes_Descending unary
  alias visit_Arel_Nodes_UnqualifiedColumn unary
  alias visit_Arel_Nodes_OptimizerHints unary
  alias visit_Arel_Nodes_ValuesList unary
  private def function: (untyped o) -> untyped
  alias visit_Arel_Nodes_Avg function
  alias visit_Arel_Nodes_Exists function
  alias visit_Arel_Nodes_Max function
  alias visit_Arel_Nodes_Min function
  alias visit_Arel_Nodes_Sum function
  private def visit_Arel_Nodes_NamedFunction: (untyped o) -> untyped
  private def visit_Arel_Nodes_Count: (untyped o) -> untyped
  private def visit_Arel_Nodes_Case: (untyped o) -> untyped
  private def nary: (untyped o) -> untyped
  alias visit_Arel_Nodes_And nary
  private def binary: (untyped o) -> untyped
  alias visit_Arel_Nodes_As binary
  alias visit_Arel_Nodes_Assignment binary
  alias visit_Arel_Nodes_Between binary
  alias visit_Arel_Nodes_Concat binary
  alias visit_Arel_Nodes_DeleteStatement binary
  alias visit_Arel_Nodes_DoesNotMatch binary
  alias visit_Arel_Nodes_Equality binary
  alias visit_Arel_Nodes_FullOuterJoin binary
  alias visit_Arel_Nodes_GreaterThan binary
  alias visit_Arel_Nodes_GreaterThanOrEqual binary
  alias visit_Arel_Nodes_In binary
  alias visit_Arel_Nodes_InfixOperation binary
  alias visit_Arel_Nodes_JoinSource binary
  alias visit_Arel_Nodes_InnerJoin binary
  alias visit_Arel_Nodes_LessThan binary
  alias visit_Arel_Nodes_LessThanOrEqual binary
  alias visit_Arel_Nodes_Matches binary
  alias visit_Arel_Nodes_NotEqual binary
  alias visit_Arel_Nodes_NotIn binary
  alias visit_Arel_Nodes_NotRegexp binary
  alias visit_Arel_Nodes_IsNotDistinctFrom binary
  alias visit_Arel_Nodes_IsDistinctFrom binary
  alias visit_Arel_Nodes_Or binary
  alias visit_Arel_Nodes_OuterJoin binary
  alias visit_Arel_Nodes_Regexp binary
  alias visit_Arel_Nodes_RightOuterJoin binary
  alias visit_Arel_Nodes_TableAlias binary
  alias visit_Arel_Nodes_When binary
  private def visit_Arel_Nodes_StringJoin: (untyped o) -> untyped
  private def visit_Arel_Attribute: (untyped o) -> untyped
  alias visit_Arel_Attributes_Integer visit_Arel_Attribute
  alias visit_Arel_Attributes_Float visit_Arel_Attribute
  alias visit_Arel_Attributes_String visit_Arel_Attribute
  alias visit_Arel_Attributes_Time visit_Arel_Attribute
  alias visit_Arel_Attributes_Boolean visit_Arel_Attribute
  alias visit_Arel_Attributes_Attribute visit_Arel_Attribute
  alias visit_Arel_Attributes_Decimal visit_Arel_Attribute
  private def visit_Arel_Table: (untyped o) -> untyped
  private def terminal: (untyped o) -> nil
  alias visit_ActiveSupport_Multibyte_Chars terminal
  alias visit_ActiveSupport_StringInquirer terminal
  alias visit_Arel_Nodes_Lock terminal
  alias visit_Arel_Nodes_Node terminal
  alias visit_Arel_Nodes_SqlLiteral terminal
  alias visit_Arel_Nodes_BindParam terminal
  alias visit_Arel_Nodes_Window terminal
  alias visit_Arel_Nodes_True terminal
  alias visit_Arel_Nodes_False terminal
  alias visit_BigDecimal terminal
  alias visit_Class terminal
  alias visit_Date terminal
  alias visit_DateTime terminal
  alias visit_FalseClass terminal
  alias visit_Float terminal
  alias visit_Integer terminal
  alias visit_NilClass terminal
  alias visit_String terminal
  alias visit_Symbol terminal
  alias visit_Time terminal
  alias visit_TrueClass terminal
  private def visit_Arel_Nodes_InsertStatement: (untyped o) -> untyped
  private def visit_Arel_Nodes_SelectCore: (untyped o) -> untyped
  private def visit_Arel_Nodes_SelectStatement: (untyped o) -> untyped
  private def visit_Arel_Nodes_UpdateStatement: (untyped o) -> untyped
  private def visit_Arel_Nodes_Comment: (untyped o) -> untyped
  private def visit_Array: (untyped o) -> untyped
  alias visit_Set visit_Array
  private def visit_Hash: (untyped o) -> untyped
  private def get_dispatch_cache: () -> untyped
  DISPATCH: Hash[untyped, untyped]
end
