# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class Arel::Visitors::Visitor
  def initialize: () -> void
  def accept: (untyped object, ?untyped? collector) -> untyped
  private def self.dispatch_cache: () -> untyped
  private def get_dispatch_cache: () -> untyped
  private def visit: (untyped object, ?untyped? collector) -> untyped
  attr_reader dispatch: untyped
end
