# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActiveRecord::Reflection::HasOneReflection < ::ActiveRecord::Reflection::AssociationReflection
  def macro: () -> :has_one
  def has_one?: () -> true
  def association_class: () -> untyped
  private def calculate_constructable: (untyped macro, untyped options) -> untyped
end
