# !!! GENERATED CODE !!!
# Please see generators/rails-generator

module ActiveRecord::Scoping::ClassMethods
  def current_scope: (?bool skip_inherited_scope) -> untyped

  def current_scope=: (untyped scope) -> untyped

  # Collects attributes from scopes that should be applied when creating
  # an AR instance for the particular class this is called on.
  def scope_attributes: () -> untyped

  # Are there attributes associated with this scope?
  def scope_attributes?: () -> untyped
end
