# !!! GENERATED CODE !!!
# Please see generators/rails-generator

module ActiveRecord::AttributeMethods::TimeZoneConversion::ClassMethods
  def define_attribute: (untyped name, untyped cast_type) -> untyped
  private def create_time_zone_conversion_attribute?: (untyped name, untyped cast_type) -> untyped
end
