# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActiveSupport::InheritableOptions < ::ActiveSupport::OrderedOptions
  def initialize: (?untyped? parent) -> void
  def inheritable_copy: () -> untyped
end
