# !!! GENERATED CODE !!!
# Please see generators/rails-generator

module ActiveSupport::Tryable : BasicObject
  def try: (?untyped? method_name, *untyped args) { (untyped) -> untyped } -> (untyped | untyped | nil)
  def try!: (?untyped? method_name, *untyped args) { (untyped) -> untyped } -> untyped
end
