# !!! GENERATED CODE !!!
# Please see generators/rails-generator

module ActiveSupport::XmlMini_LibXML
  # Parse an XML Document string or IO into a simple hash using libxml.
  # data::
  #   XML Document string or IO to parse
  def parse: (untyped data) -> untyped
end
