# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActionView::CollectionRenderer::PreloadCollectionIterator < ::ActionView::CollectionRenderer::SameCollectionIterator
  def initialize: (untyped collection, untyped path, untyped variables, untyped relation) -> void
  def from_collection: (untyped collection) -> untyped
  def each_with_info: () -> untyped
end
