# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActiveStorage::VariantRecord::ActiveRecord_AssociationRelation < ::ActiveRecord::AssociationRelation
  include ActiveRecord::Delegation::ClassSpecificRelation
  include ActiveStorage::VariantRecord::GeneratedRelationMethods
  extend ActiveRecord::Delegation::ClassSpecificRelation::ClassMethods
end
