# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class BigDecimal < ::Numeric
  prepend ActiveSupport::BigDecimalWithDefaultFormat
  prepend ActiveSupport::NumericWithFormat
  prepend ActiveSupport::DeprecatedNumericWithFormat
end
