# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActiveJob::Serializers::ModuleSerializer < ::ActiveJob::Serializers::ObjectSerializer
  def serialize: (untyped constant) -> untyped
  def deserialize: (untyped hash) -> untyped
  private def klass: () -> untyped
end
