# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActiveJob::Serializers::TimeObjectSerializer < ::ActiveJob::Serializers::ObjectSerializer
  def serialize: (untyped time) -> untyped
  NANO_PRECISION: Integer
end
