# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActiveSupport::Notifications::InstrumentationRegistry
  def initialize: () -> void
  def instrumenter_for: (untyped notifier) -> untyped
  extend ActiveSupport::PerThreadRegistry
end
