# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActiveRecord::Type::HashLookupTypeMap < ::ActiveRecord::Type::TypeMap
  def alias_type: (untyped `type`, untyped alias_type) -> untyped
  def key?: (untyped key) -> untyped
  def keys: () -> untyped
  private def perform_fetch: (untyped `type`, *untyped args) ?{ () -> untyped } -> untyped
end
