# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActiveRecord::Type::UnsignedInteger < ::ActiveModel::Type::Integer
  private def max_value: () -> untyped
  private def min_value: () -> 0
end
