# !!! GENERATED CODE !!!
# Please see generators/rails-generator

module ActiveJob::QueueName::ClassMethods
  # Specifies the name of the queue to process the job on.
  #
  #   class PublishToFeedJob < ActiveJob::Base
  #     queue_as :feeds
  #
  #     def perform(post)
  #       post.to_feed!
  #     end
  #   end
  def queue_as: (?untyped? part_name) ?{ () -> untyped } -> untyped

  def queue_name_from_part: (untyped part_name) -> untyped

  def self.queue_name_prefix: () -> untyped

  def queue_name_prefix: () -> untyped

  def self.default_queue_name: () -> untyped

  def default_queue_name: () -> untyped

  def self.queue_name_prefix=: (untyped val) -> untyped

  def queue_name_prefix=: (untyped val) -> untyped

  def self.default_queue_name=: (untyped val) -> untyped

  def default_queue_name=: (untyped val) -> untyped
end
