# !!! GENERATED CODE !!!
# Please see generators/rails-generator

module ActiveModel::Conversion::ClassMethods
  # Provide a class level cache for #to_partial_path. This is an
  # internal method and should not be accessed directly.
  def _to_partial_path: () -> untyped
end
