# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActiveRecord::Reflection::HasAndBelongsToManyReflection < ::ActiveRecord::Reflection::AssociationReflection
  def macro: () -> :has_and_belongs_to_many
  def collection?: () -> true
end
