# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActiveRecord::DatabaseConfigurations
  def initialize: (?::Hash[untyped, untyped] configurations) -> void
  # Collects the configs for the environment and optionally the specification
  # name passed in. To include replica configurations pass <tt>include_replicas: true</tt>.
  #
  # If a name is provided a single DatabaseConfig object will be
  # returned, otherwise an array of DatabaseConfig objects will be
  # returned that corresponds with the environment and type requested.
  #
  # ==== Options
  #
  # * <tt>env_name:</tt> The environment name. Defaults to +nil+ which will collect
  #   configs for all environments.
  # * <tt>name:</tt> The db config name (i.e. primary, animals, etc.). Defaults
  #   to +nil+. If no +env_name+ is specified the config for the default env and the
  #   passed +name+ will be returned.
  # * <tt>include_replicas:</tt> Determines whether to include replicas in
  #   the returned list. Most of the time we're only iterating over the write
  #   connection (i.e. migrations don't need to run for the write and read connection).
  #   Defaults to +false+.
  def configs_for: (?env_name: untyped?, ?spec_name: untyped?, ?name: untyped?, ?include_replicas: bool) -> untyped
  # Returns the config hash that corresponds with the environment
  #
  # If the application has multiple databases +default_hash+ will
  # return the first config hash for the environment.
  #
  #   { database: "my_db", adapter: "mysql2" }
  def default_hash: (?untyped env) -> untyped
  alias [] default_hash
  # Returns a single DatabaseConfig object based on the requested environment.
  #
  # If the application has multiple databases +find_db_config+ will return
  # the first DatabaseConfig for the environment.
  def find_db_config: (untyped env) -> untyped
  # A primary configuration is one that is named primary or if there is
  # no primary, the first configuration for an environment will be treated
  # as primary. This is used as the "default" configuration and is used
  # when the application needs to treat one configuration differently. For
  # example, when Rails dumps the schema, the primary configuration's schema
  # file will be named `schema.rb` instead of `primary_schema.rb`.
  def primary?: (untyped name) -> (true | untyped)
  # Returns the DatabaseConfigurations object as a Hash.
  def to_h: () -> untyped
  # Checks if the application's configurations are empty.
  #
  # Aliased to blank?
  def empty?: () -> untyped
  alias blank? empty?
  # Returns fully resolved connection, accepts hash, string or symbol.
  # Always returns a DatabaseConfiguration::DatabaseConfig
  #
  # == Examples
  #
  # Symbol representing current environment.
  #
  #   DatabaseConfigurations.new("production" => {}).resolve(:production)
  #   # => DatabaseConfigurations::HashConfig.new(env_name: "production", config: {})
  #
  # One layer deep hash of connection values.
  #
  #   DatabaseConfigurations.new({}).resolve("adapter" => "sqlite3")
  #   # => DatabaseConfigurations::HashConfig.new(config: {"adapter" => "sqlite3"})
  #
  # Connection URL.
  #
  #   DatabaseConfigurations.new({}).resolve("postgresql://localhost/foo")
  #   # => DatabaseConfigurations::UrlConfig.new(config: {"adapter" => "postgresql", "host" => "localhost", "database" => "foo"})
  def resolve: (untyped config) -> untyped
  private def default_env: () -> untyped
  private def env_with_configs: (?untyped? env) -> untyped
  private def build_configs: (untyped configs) -> untyped
  private def walk_configs: (untyped env_name, untyped config) -> untyped
  private def resolve_symbol_connection: (untyped name) -> untyped
  private def build_configuration_sentence: () -> untyped
  private def build_db_config_from_raw_config: (untyped env_name, untyped name, untyped config) -> untyped
  private def build_db_config_from_string: (untyped env_name, untyped name, untyped config) -> untyped
  private def build_db_config_from_hash: (untyped env_name, untyped name, untyped config) -> untyped
  private def merge_db_environment_variables: (untyped current_env, untyped configs) -> untyped
  private def environment_url_config: (untyped env, untyped name, untyped config) -> (nil | untyped)
  private def environment_value_for: (untyped name) -> untyped
  attr_reader configurations: untyped
  # defined by `delegate` to: untyped#configurations
  def any?: (*untyped, **untyped) -> untyped
end
