# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActiveRecord::InverseOfAssociationNotFoundError < ::ActiveRecord::ActiveRecordError
  def initialize: (?untyped? reflection, ?untyped? associated_class) -> void
  prepend DidYouMean::Correctable
  attr_reader reflection: untyped
  attr_reader associated_class: untyped
end
