# !!! GENERATED CODE !!!
# Please see generators/rails-generator

module ActiveRecord::AutosaveAssociation::ClassMethods
  private def define_non_cyclic_method: (untyped name) ?{ () -> untyped } -> (nil | untyped)
  # Adds validation and save callbacks for the association as specified by
  # the +reflection+.
  #
  # For performance reasons, we don't check whether to validate at runtime.
  # However the validation and callback methods are lazy and those methods
  # get created when they are invoked for the very first time. However,
  # this can change, for instance, when using nested attributes, which is
  # called _after_ the association has been defined. Since we don't want
  # the callbacks to get defined multiple times, there are guards that
  # check if the save or validation methods have already been defined
  # before actually defining them.
  private def add_autosave_association_callbacks: (untyped reflection) -> untyped
  private def define_autosave_validation_callbacks: (untyped reflection) -> untyped
end
