# !!! GENERATED CODE !!!
# Please see generators/rails-generator

module ActionController::ContentSecurityPolicy::ClassMethods
  def content_security_policy: (?bool enabled, **untyped options) { (untyped) -> untyped } -> untyped
  def content_security_policy_report_only: (?bool report_only, **untyped options) -> untyped
end
