# !!! GENERATED CODE !!!
# Please see generators/rails-generator

module AbstractController::Collector
  def self.generate_method_for_mime: (untyped mime) -> untyped
  private def method_missing: (untyped symbol) ?{ () -> untyped } -> untyped
end
