# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActionController::MimeResponds::Collector::VariantCollector
  def initialize: (?untyped? variant) -> void
  def any: (*untyped args) ?{ () -> untyped } -> (untyped | nil)
  alias all any
  def method_missing: (untyped name, *untyped args) ?{ () -> untyped } -> (untyped | nil)
  def variant: () -> untyped
  private def variant_key: () -> untyped
end
