# !!! GENERATED CODE !!!
# Please see generators/rails-generator

module ActionController::Testing::Functional
  def clear_instance_variables_between_requests: () -> untyped
  def recycle!: () -> untyped
end
