# !!! GENERATED CODE !!!
# Please see generators/rails-generator

module ActiveRecord::Associations::ForeignAssociation
  def foreign_key_present?: () -> (untyped | false)
  def nullified_owner_attributes: () -> untyped
end
