# !!! GENERATED CODE !!!
# Please see generators/rails-generator

module ActiveStorage::Blob::Identifiable
  def identify: () -> untyped
  def identify_without_saving: () -> (untyped | nil)
  def identified?: () -> untyped
  private def identify_content_type: () -> untyped
  private def download_identifiable_chunk: () -> (untyped | "")
end
