# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class Arel::DeleteManager < ::Arel::TreeManager
  def initialize: () -> void
  def from: (untyped relation) -> self
  include Arel::TreeManager::StatementMethods
end
