# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActiveSupport::Notifications::Fanout::Subscribers::Matcher::AllMessages
  def ===: (untyped name) -> true
  def unsubscribe!: () -> false
end
