# !!! GENERATED CODE !!!
# Please see generators/rails-generator

module ActiveRecord::Delegation::ClassSpecificRelation
  private def method_missing: (untyped method, *untyped args) ?{ () -> untyped } -> untyped
  extend ActiveSupport::Concern
end
