# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActiveRecord::Delegation::GeneratedRelationMethods < ::Module
  def generate_method: (untyped method) -> untyped
  include Mutex_m
end
