# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActionDispatch::Journey::Path::Pattern
  def self.from_string: (untyped string) -> untyped
  def self.build: (untyped path, untyped requirements, untyped separators, untyped anchored) -> untyped
  def initialize: (untyped ast, untyped requirements, untyped separators, untyped anchored) -> void
  def build_formatter: () -> untyped
  def eager_load!: () -> nil
  def ast: () -> untyped
  def names: () -> untyped
  def required_names: () -> untyped
  def optional_names: () -> untyped
  def match: (untyped other) -> (nil | untyped)
  alias =~ match
  def source: () -> untyped
  def to_regexp: () -> untyped
  private def regexp_visitor: () -> untyped
  private def offsets: () -> untyped
  attr_reader spec: untyped
  attr_reader requirements: untyped
  attr_reader anchored: untyped
end
