# !!! GENERATED CODE !!!
# Please see generators/rails-generator

module ActiveRecord::Encryption::ExtendedDeterministicUniquenessValidator::EncryptedUniquenessValidator
  def validate_each: (untyped record, untyped attribute, untyped value) -> untyped
end
