# !!! GENERATED CODE !!!
# Please see generators/rails-generator

module ActiveModel::Type
  # Add a new type to the registry, allowing it to be referenced as a
  # symbol by {attribute}[rdoc-ref:Attributes::ClassMethods#attribute].
  def self.register: (untyped type_name, ?untyped? klass) ?{ () -> untyped } -> untyped
  def self.lookup: (*untyped) ?{ () -> untyped } -> untyped
  def self.default_value: () -> untyped
  attr_accessor self.registry: untyped
end
