# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActiveRecord::InternalMetadata::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
  include ActiveRecord::Delegation::ClassSpecificRelation
  include ActiveRecord::InternalMetadata::GeneratedRelationMethods
  extend ActiveRecord::Delegation::ClassSpecificRelation::ClassMethods
end
