# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActiveRecord::AssociationNotFoundError < ::ActiveRecord::ConfigurationError
  def initialize: (?untyped? record, ?untyped? association_name) -> void
  def corrections: () -> (untyped | ::Array[untyped])
  include DidYouMean::Correctable
  attr_reader record: untyped
  attr_reader association_name: untyped
end
