# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActiveRecord::DuplicateMigrationVersionError < ::ActiveRecord::MigrationError
  def initialize: (?untyped? version) -> void
end
