# !!! GENERATED CODE !!!
# Please see generators/rails-generator

module ActiveRecord::Explain
  # Executes the block with the collect flag enabled. Queries are collected
  # asynchronously by the subscriber and returned.
  def collecting_queries_for_explain: () { () -> untyped } -> untyped
  # Makes the adapter execute EXPLAIN for the tuples of queries and bindings.
  # Returns a formatted string ready to be logged.
  def exec_explain: (untyped queries) -> untyped
  private def render_bind: (untyped attr) -> ::Array[untyped]
end
