# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActiveRecord::RecordNotDestroyed < ::ActiveRecord::ActiveRecordError
  def initialize: (?untyped? message, ?untyped? record) -> void
  attr_reader record: untyped
end
