# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActiveRecord::SoleRecordExceeded < ::ActiveRecord::ActiveRecordError
  def initialize: (?untyped? record) -> void
  attr_reader record: untyped
end
