# !!! GENERATED CODE !!!
# Please see generators/rails-generator

module ActionView::RenderParser::RipperASTParser
  def parse_render_nodes: (untyped code) -> untyped
  extend ActionView::RenderParser::RipperASTParser
end
