# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActiveRecord::Validations::LengthValidator < ::ActiveModel::Validations::LengthValidator
  def validate_each: (untyped record, untyped attribute, untyped association_or_value) -> untyped
end
