# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActiveJob::Serializers::TimeWithZoneSerializer < ::ActiveJob::Serializers::TimeObjectSerializer
  def deserialize: (untyped hash) -> untyped
  private def klass: () -> untyped
end
