# !!! GENERATED CODE !!!
# Please see generators/rails-generator

module ActiveSupport::ForkTracker::CoreExtPrivate : BasicObject
  private def fork: () -> untyped
  include ActiveSupport::ForkTracker::CoreExt
end
