# !!! GENERATED CODE !!!
# Please see generators/rails-generator

module ActionController::HttpAuthentication::Token::ControllerMethods
  # Authenticate using an HTTP Bearer token, or otherwise render an HTTP
  # header requesting the client to send a Bearer token.
  #
  # See ActionController::HttpAuthentication::Token for example usage.
  def authenticate_or_request_with_http_token: (?::String realm, ?untyped? message) ?{ () -> untyped } -> untyped
  # Authenticate using an HTTP Bearer token. Returns true if
  # authentication is successful, false otherwise.
  def authenticate_with_http_token: () ?{ () -> untyped } -> untyped
  # Render an HTTP header requesting the client to send a Bearer token for
  # authentication.
  def request_http_token_authentication: (?::String realm, ?untyped? message) -> untyped
end
