# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActiveSupport::DescendantsTracker::DescendantsArray
  def initialize: () -> void
  def initialize_copy: (untyped orig) -> untyped
  def <<: (untyped klass) -> untyped
  def each: () { (untyped) -> untyped } -> self
  def refs_size: () -> untyped
  def cleanup!: () -> untyped
  def reject!: () { (untyped) -> untyped } -> untyped
end
