# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActionDispatch::Journey::GTG::Simulator
  def initialize: (untyped transition_table) -> void
  def memos: (untyped string) { () -> untyped } -> untyped
  attr_reader tt: untyped
  INITIAL_STATE: Array[Integer]
end
