# !!! GENERATED CODE !!!
# Please see generators/rails-generator

module ActiveJob::Enqueuing::ClassMethods
  # Push a job onto the queue. The arguments must be legal JSON types
  # (+string+, +int+, +float+, +nil+, +true+, +false+, +hash+ or +array+) or
  # GlobalID::Identification instances. Arbitrary Ruby objects
  # are not supported.
  #
  # Returns an instance of the job class queued with arguments available in
  # Job#arguments.
  def perform_later: (*untyped args) -> untyped

  private def job_or_instantiate: (*untyped args) -> untyped
end
