# !!! GENERATED CODE !!!
# Please see generators/rails-generator

module ActiveSupport::Dependencies::ZeitwerkIntegration::Inflector
  def self.camelize: (untyped basename, untyped _abspath) -> untyped
  def self.inflect: (untyped overrides) -> untyped
end
