# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class Mime::Type::AcceptItem
  alias to_s name
  def initialize: (untyped index, untyped name, ?untyped? q) -> void
  def <=>: (untyped item) -> untyped
  attr_accessor index: untyped
  attr_accessor name: untyped
  attr_accessor q: untyped
end
