# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActiveStorage::Analyzer::NullAnalyzer < ::ActiveStorage::Analyzer
  def self.accept?: (untyped blob) -> true
  def self.analyze_later?: () -> false
  def metadata: () -> ::Hash[untyped, untyped]
end
