# !!! GENERATED CODE !!!
# Please see generators/rails-generator

module AbstractController::Callbacks
  # Override <tt>AbstractController::Base#process_action</tt> to run the
  # <tt>process_action</tt> callbacks around the normal behavior.
  def process_action: () -> untyped
  include ActiveSupport::Callbacks
  extend ActiveSupport::Concern
end
