# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActionView::Helpers::NumberHelper::InvalidNumberError < ::StandardError
  def initialize: (untyped number) -> void
  attr_accessor number: untyped
end
