# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActionController::Live::Response < ::ActionDispatch::Response
  private def before_committed: () -> untyped
  private def build_buffer: (untyped response, untyped body) -> untyped
end
