# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActionView::Helpers::TagHelper::TagBuilder
  def initialize: (untyped view_context) -> void
  def tag_string: (untyped name, ?untyped? content, **untyped options) ?{ () -> untyped } -> untyped
  def content_tag_string: (untyped name, untyped content, untyped options, ?bool escape) -> untyped
  def tag_options: (untyped options, ?bool escape) -> (nil | untyped)
  def boolean_tag_option: (untyped key) -> ::String
  def tag_option: (untyped key, untyped value, untyped escape) -> ::String
  private def prefix_tag_option: (untyped prefix, untyped key, untyped value, untyped escape) -> untyped
  private def respond_to_missing?: (*untyped args) -> true
  private def handle_deprecated_escape_options: (untyped options) -> (true | untyped)
  private def method_missing: (untyped called, *untyped args, **untyped options) ?{ () -> untyped } -> untyped
  include ActionView::Helpers::CaptureHelper
  include ActionView::Helpers::OutputSafetyHelper
  VOID_ELEMENTS: Set[Symbol]
end
