# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActiveRecord::FixtureSet::ModelMetadata
  def initialize: (untyped model_class) -> void
  def primary_key_name: () -> untyped
  def primary_key_type: () -> untyped
  def has_primary_key_column?: () -> untyped
  def timestamp_column_names: () -> untyped
  def inheritance_column_name: () -> untyped
end
