# !!! GENERATED CODE !!!
# Please see generators/rails-generator

module ActiveJob
  # Returns the currently loaded version of Active Job as a <tt>Gem::Version</tt>.
  def self.gem_version: () -> untyped
  # Returns the currently loaded version of Active Job as a <tt>Gem::Version</tt>.
  def self.version: () -> untyped
  extend ActiveSupport::Autoload
end
