# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class Arel::Attributes::Attribute
  # #
  # Create a node for lowering this attribute
  def lower: () -> untyped
  def type_cast_for_database: (untyped value) -> untyped
  def able_to_type_cast?: () -> untyped
  include Arel::Expressions
  include Arel::Predications
  include Arel::AliasPredication
  include Arel::OrderPredications
  include Arel::Math
end
