# !!! GENERATED CODE !!!
# Please see generators/rails-generator

module ActiveRecord::AttributeMethods::PrimaryKey
  # Returns this record's primary key value wrapped in an array if one is
  # available.
  def to_key: () -> untyped

  # Returns the primary key value.
  def id: () -> untyped

  # Sets the primary key value.
  def id=: (untyped value) -> untyped

  # Queries the primary key value.
  def id?: () -> untyped

  # Returns the primary key value before type cast.
  def id_before_type_cast: () -> untyped

  # Returns the primary key previous value.
  def id_was: () -> untyped

  def id_in_database: () -> untyped

  private def attribute_method?: (untyped attr_name) -> untyped

  extend ActiveSupport::Concern
end
