# !!! GENERATED CODE !!!
# Please see generators/rails-generator

module ActionController::ContentSecurityPolicy::ClassMethods
  # Overrides parts of the globally configured Content-Security-Policy
  # header:
  #
  #   class PostsController < ApplicationController
  #     content_security_policy do |policy|
  #       policy.base_uri "https://www.example.com"
  #     end
  #   end
  #
  # Options can be passed similar to +before_action+. For example, pass
  # <tt>only: :index</tt> to override the header on the index action only:
  #
  #   class PostsController < ApplicationController
  #     content_security_policy(only: :index) do |policy|
  #       policy.default_src :self, :https
  #     end
  #   end
  #
  # Pass +false+ to remove the Content-Security-Policy header:
  #
  #   class PostsController < ApplicationController
  #     content_security_policy false, only: :index
  #   end
  def content_security_policy: (?bool enabled, **untyped options) { (untyped) -> untyped } -> untyped
  # Overrides the globally configured Content-Security-Policy-Report-Only
  # header:
  #
  #   class PostsController < ApplicationController
  #     content_security_policy_report_only only: :index
  #   end
  #
  # Pass +false+ to remove the Content-Security-Policy-Report-Only header:
  #
  #   class PostsController < ApplicationController
  #     content_security_policy_report_only false, only: :index
  #   end
  def content_security_policy_report_only: (?bool report_only, **untyped options) -> untyped
end
