# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActiveStorage::Previewer::VideoPreviewer < ::ActiveStorage::Previewer
  def self.accept?: (untyped blob) -> untyped
  def self.ffmpeg_exists?: () -> untyped
  def self.ffmpeg_path: () -> untyped
  def preview: () { (io: untyped, filename: untyped, content_type: untyped) -> untyped } -> untyped
  private def draw_relevant_frame_from: (untyped file) ?{ () -> untyped } -> untyped
end
