# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActiveJob::QueueAdapters::QuAdapter
  def enqueue: (untyped job, *untyped args) -> untyped
  def enqueue_at: (untyped job, untyped timestamp, *untyped args) -> untyped
end
