# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActiveStorage::Attached::Changes::CreateMany
  def initialize: (untyped name, untyped record, untyped attachables) -> void
  def attachments: () -> untyped
  def blobs: () -> untyped
  def upload: () -> untyped
  def save: () -> untyped
  private def subchanges: () -> untyped
  private def build_subchange_from: (untyped attachable) -> untyped
  private def assign_associated_attachments: () -> untyped
  private def reset_associated_blobs: () -> untyped
  attr_reader name: untyped
  attr_reader record: untyped
  attr_reader attachables: untyped
end
