# !!! GENERATED CODE !!!
# Please see generators/rails-generator

module ActionDispatch::SystemTesting::TestHelpers::ScreenshotHelper
  # Takes a screenshot of the current page in the browser.
  #
  # +take_screenshot+ can be used at any point in your system tests to take
  # a screenshot of the current state. This can be useful for debugging or
  # automating visual testing.
  #
  # The screenshot will be displayed in your console, if supported.
  #
  # You can set the +RAILS_SYSTEM_TESTING_SCREENSHOT+ environment variable to
  # control the output. Possible values are:
  # * [+simple+ (default)]    Only displays the screenshot path.
  #                           This is the default value.
  # * [+inline+]              Display the screenshot in the terminal using the
  #                           iTerm image protocol (https://iterm2.com/documentation-images.html).
  # * [+artifact+]            Display the screenshot in the terminal, using the terminal
  #                           artifact format (https://buildkite.github.io/terminal-to-html/inline-images/).
  def take_screenshot: () -> untyped
  # Takes a screenshot of the current page in the browser if the test
  # failed.
  #
  # +take_failed_screenshot+ is included in <tt>application_system_test_case.rb</tt>
  # that is generated with the application. To take screenshots when a test
  # fails add +take_failed_screenshot+ to the teardown block before clearing
  # sessions.
  def take_failed_screenshot: () -> (untyped | nil)
  private def image_name: () -> untyped
  private def image_path: () -> untyped
  private def absolute_image_path: () -> untyped
  private def save_image: () -> untyped
  private def output_type: () -> untyped
  private def display_image: () -> untyped
  private def inline_base64: (untyped path) -> untyped
  private def failed?: () -> untyped
  private def supports_screenshot?: () -> untyped
end
