# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActiveStorage::Reflection::HasManyAttachedReflection < ::ActiveRecord::Reflection::MacroReflection
  def macro: () -> :has_many_attached
end
