# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class Mime::Type::AcceptList
  def self.sort!: (untyped list) -> untyped
  def self.find_item_by_name: (untyped array, untyped name) -> untyped
end
