# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActiveModel::NullMutationTracker
  def changed_attribute_names: () -> ::Array[untyped]
  def changed_values: () -> ::Hash[untyped, untyped]
  def changes: () -> ::Hash[untyped, untyped]
  def change_to_attribute: (untyped attr_name) -> nil
  def any_changes?: () -> false
  def changed?: () -> false
  def changed_in_place?: () -> false
  def forget_change: () -> nil
  def original_value: () -> nil
  def force_change: () -> nil
  include Singleton
  extend Singleton::SingletonClassMethods
end
