# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActiveModel::Attribute::WithCastValue < ::ActiveModel::Attribute
  def type_cast: (untyped value) -> untyped
  def changed_in_place?: () -> false
end
