# !!! GENERATED CODE !!!
# Please see generators/rails-generator

module ActiveRecord::AttributeMethods::PrimaryKey::ClassMethods
  def instance_method_already_implemented?: (untyped method_name) -> untyped

  def dangerous_attribute_method?: (untyped method_name) -> untyped

  # Defines the primary key field -- can be overridden in subclasses.
  # Overwriting will negate any effect of the +primary_key_prefix_type+
  # setting, though.
  def primary_key: () -> untyped

  # Returns a quoted version of the primary key name, used to construct
  # SQL statements.
  def quoted_primary_key: () -> untyped

  def reset_primary_key: () -> untyped

  def get_primary_key: (untyped base_name) -> (untyped | untyped | untyped | "id")

  # Sets the name of the primary key column.
  #
  #   class Project < ActiveRecord::Base
  #     self.primary_key = 'sysid'
  #   end
  #
  # You can also define the #primary_key method yourself:
  #
  #   class Project < ActiveRecord::Base
  #     def self.primary_key
  #       'foo_' + super
  #     end
  #   end
  #
  #   Project.primary_key # => "foo_id"
  def primary_key=: (untyped value) -> untyped

  private def suppress_composite_primary_key: (untyped pk) -> untyped

  ID_ATTRIBUTE_METHODS: Set[String]
end
