# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActionController::ParamsWrapper::Options
  def self.from_hash: (untyped hash) -> untyped
  def initialize: (untyped name, untyped format, untyped `include`, untyped exclude, untyped klass, untyped model) -> void
  def model: () -> untyped
  def include: () -> untyped
  def name: () -> untyped
  # Determine the wrapper model from the controller's name. By convention,
  # this could be done by trying to find the defined model that has the
  # same singular name as the controller. For example, +UsersController+
  # will try to find if the +User+ model exists.
  #
  # This method also does namespace lookup. Foo::Bar::UsersController will
  # try to find Foo::Bar::User, Foo::User and finally User.
  private def _default_wrap_model: () -> (nil | untyped)
  include Mutex_m
end
