# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActiveSupport::NumberHelper::NumberToCurrencyConverter < ::ActiveSupport::NumberHelper::NumberConverter
  def convert: () -> untyped
  private def options: () -> untyped
  private def i18n_opts: () -> untyped
end
