# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActiveSupport::NumberHelper::RoundingHelper
  def initialize: (untyped options) -> void
  def round: (untyped number) -> untyped
  def digit_count: (untyped number) -> (1 | untyped)
  private def convert_to_decimal: (untyped number) -> untyped
  private def absolute_precision: (untyped number) -> untyped
  attr_reader options: untyped
end
