# !!! GENERATED CODE !!!
# Please see generators/rails-generator

module ActiveModel::SecurePassword
  extend ActiveSupport::Concern
  attr_accessor self.min_cost: untyped
  MAX_PASSWORD_LENGTH_ALLOWED: Integer
end
