# !!! GENERATED CODE !!!
# Please see generators/rails-generator

module ActiveSupport::Deprecation::InstanceDelegator::ClassMethods
  def include: (untyped included_module) -> untyped

  def method_added: (untyped method_name) -> untyped
end
