# !!! GENERATED CODE !!!
# Please see generators/rails-generator

module ActionController::PermissionsPolicy::ClassMethods
  def permissions_policy: (**untyped options) { (untyped) -> untyped } -> untyped
end
