# !!! GENERATED CODE !!!
# Please see generators/rails-generator

module ActiveModel
  # Returns the version of the currently loaded \Active \Model as a <tt>Gem::Version</tt>
  def self.gem_version: () -> untyped
  # Returns the version of the currently loaded \Active \Model as a <tt>Gem::Version</tt>
  def self.version: () -> untyped
  def self.eager_load!: () -> untyped
  extend ActiveSupport::Autoload
end
