# !!! GENERATED CODE !!!
# Please see generators/rails-generator

module URI::RFC2396_REGEXP::PATTERN
  ABS_PATH: String

  ABS_URI: String

  ALNUM: String

  ALPHA: String

  DOMLABEL: String

  ESCAPED: String

  FRAGMENT: String

  HEX: String

  HIER_PART: String

  HOST: String

  HOSTNAME: String

  HOSTPORT: String

  IPV4ADDR: String

  IPV6ADDR: String

  IPV6REF: String

  NET_PATH: String

  OPAQUE_PART: String

  PATH_SEGMENTS: String

  PORT: String

  QUERY: String

  REG_NAME: String

  REL_PATH: String

  REL_SEGMENT: String

  REL_URI: String

  RESERVED: String

  SCHEME: String

  TOPLABEL: String

  UNRESERVED: String

  URIC: String

  URIC_NO_SLASH: String

  URI_REF: String

  USERINFO: String

  X_ABS_URI: String

  X_REL_URI: String
end
