# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActionDispatch::SystemTesting::Driver
  def initialize: (untyped driver_type, **untyped options) ?{ () -> untyped } -> void
  def use: () -> untyped
  private def registerable?: () -> untyped
  private def register: () -> untyped
  private def browser_options: () -> untyped
  private def register_selenium: (untyped app) -> untyped
  private def register_poltergeist: (untyped app) -> untyped
  private def register_webkit: (untyped app) -> untyped
  private def register_cuprite: (untyped app) -> untyped
  private def register_rack_test: (untyped app) -> untyped
  private def setup: () -> untyped
end
