# !!! GENERATED CODE !!!
# Please see generators/rails-generator

module ActiveRecord::SecureToken::ClassMethods
  # Example using #has_secure_token
  #
  #   # Schema: User(token:string, auth_token:string)
  #   class User < ActiveRecord::Base
  #     has_secure_token
  #     has_secure_token :auth_token
  #   end
  #
  #   user = User.new
  #   user.save
  #   user.token # => "pX27zsMN2ViQKta1bGfLmVJE"
  #   user.auth_token # => "77TMHrHJFvFDwodq8w7Ev2m7"
  #   user.regenerate_token # => true
  #   user.regenerate_auth_token # => true
  #
  # <tt>SecureRandom::base58</tt> is used to generate the 24-character unique token, so collisions are highly unlikely.
  #
  # Note that it's still possible to generate a race condition in the database in the same way that
  # {validates_uniqueness_of}[rdoc-ref:Validations::ClassMethods#validates_uniqueness_of] can.
  # You're encouraged to add a unique index in the database to deal with this even more unlikely scenario.
  def has_secure_token: (?::Symbol attribute) -> untyped
  def generate_unique_secure_token: () -> untyped
end
