# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActiveRecord::Type::AdapterSpecificRegistry < ::ActiveModel::Type::Registry
  def add_modifier: (untyped options, untyped klass, **untyped args) -> untyped
  private def registration_klass: () -> untyped
  private def find_registration: (untyped symbol, *untyped args, **untyped kwargs) -> untyped
end
