# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActiveRecord::Encryption::DerivedSecretKeyProvider < ::ActiveRecord::Encryption::KeyProvider
  def initialize: (untyped passwords) -> void
end
