# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActionView::Template::LegacyTemplate < ::ActionView::Template
  def initialize: (untyped template, untyped source) -> void
  attr_reader source: untyped
end
