# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActiveRecord::FixtureSet::TableRow::HasManyThroughProxy < ::ActiveRecord::FixtureSet::TableRow::ReflectionProxy
  def rhs_key: () -> untyped
  def lhs_key: () -> untyped
  def join_table: () -> untyped
  def timestamp_column_names: () -> untyped
end
