# !!! GENERATED CODE !!!
# Please see generators/rails-generator

module ActiveModel::AttributeMethods::AttrNames
  # We want to generate the methods via module_eval rather than
  # define_method, because define_method is slower on dispatch.
  #
  # But sometimes the database might return columns with
  # characters that are not allowed in normal method names (like
  # 'my_column(omg)'. So to work around this we first define with
  # the __temp__ identifier, and then use alias method to rename
  # it to what we want.
  #
  # We are also defining a constant to hold the frozen string of
  # the attribute name. Using a constant means that we do not have
  # to allocate an object on each call to the attribute method.
  # Making it frozen means that it doesn't get duped when used to
  # key the @attributes in read_attribute.
  def self.define_attribute_accessor_method: (untyped owner, untyped attr_name, ?writer: bool) { (untyped, untyped) -> untyped } -> untyped
  DEF_SAFE_NAME: Regexp
end
