# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActiveSupport::Logger::SimpleFormatter < ::Logger::Formatter
  # This method is invoked when a log event occurs
  def call: (untyped severity, untyped timestamp, untyped progname, untyped msg) -> ::String
end
