# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActiveRecord::SchemaMigration::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
  include ActiveRecord::Delegation::ClassSpecificRelation
  include ActiveRecord::SchemaMigration::GeneratedRelationMethods
  extend ActiveRecord::Delegation::ClassSpecificRelation::ClassMethods
end
