# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActionView::SyntaxErrorInTemplate < ::ActionView::Template::Error
  def initialize: (untyped template, untyped offending_code_string) -> void
  def message: () -> ::String
  def annotated_source_code: () -> untyped
end
