# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActiveModel::Validations::AcceptanceValidator::LazilyDefineAttributes < ::Module
  def initialize: (untyped attribute_definition) -> void
end
