# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActiveRecord::Locking::LockingType < ::ActiveModel::Type::Value
  def self.new: (untyped subtype) -> untyped
  def deserialize: (untyped value) -> untyped
  def serialize: (untyped value) -> untyped
  def init_with: (untyped coder) -> untyped
  def encode_with: (untyped coder) -> untyped
end
