# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActiveRecord::Validations::NumericalityValidator < ::ActiveModel::Validations::NumericalityValidator
  def validate_each: (untyped record, untyped attribute, untyped value, ?precision: untyped?, ?scale: untyped?) -> untyped
  private def column_precision_for: (untyped record, untyped attribute) -> untyped
  private def column_scale_for: (untyped record, untyped attribute) -> untyped
end
