# !!! GENERATED CODE !!!
# Please see generators/rails-generator

module ActionDispatch::Routing::RouteSet::MountedHelpers
  include ActionDispatch::Routing::UrlFor
  extend ActiveSupport::Concern
end
