# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActionDispatch::Routing::RouteSet::StaticDispatcher < ::ActionDispatch::Routing::RouteSet::Dispatcher
  def initialize: (untyped controller_class) -> void
  private def controller: (untyped _) -> untyped
end
