# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActiveRecord::InternalMetadata::ActiveRecord_DisableJoinsAssociationRelation < ::ActiveRecord::DisableJoinsAssociationRelation
  include ActiveRecord::Delegation::ClassSpecificRelation
  include ActiveRecord::InternalMetadata::GeneratedRelationMethods
  extend ActiveRecord::Delegation::ClassSpecificRelation::ClassMethods
end
