# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActiveRecord::Store::StringKeyedHashAccessor < ::ActiveRecord::Store::HashAccessor
  def self.read: (untyped object, untyped attribute, untyped key) -> untyped
  def self.write: (untyped object, untyped attribute, untyped key, untyped value) -> untyped
end
