# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActiveRecord::AdvisoryLockBase::ActiveRecord_AssociationRelation < ::ActiveRecord::AssociationRelation
  include ActiveRecord::Delegation::ClassSpecificRelation
  include ActiveRecord::AdvisoryLockBase::GeneratedRelationMethods
  extend ActiveRecord::Delegation::ClassSpecificRelation::ClassMethods
end
