# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class AbstractController::ActionNotFound::Correction
  def initialize: (untyped error) -> void
  def corrections: () -> (untyped | ::Array[untyped])
end
