# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActionDispatch::Journey::Nodes::Literal < ::ActionDispatch::Journey::Nodes::Terminal
  def literal?: () -> true
  def type: () -> :LITERAL
end
