# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActionDispatch::Journey::Nodes::Terminal < ::ActionDispatch::Journey::Nodes::Node
  alias symbol left
  def terminal?: () -> true
end
