# !!! GENERATED CODE !!!
# Please see generators/rails-generator

module ActiveModel::Type::Helpers::Mutable
  def cast: (untyped value) -> untyped
  # +raw_old_value+ will be the `_before_type_cast` version of the
  # value (likely a string). +new_value+ will be the current, type
  # cast value.
  def changed_in_place?: (untyped raw_old_value, untyped new_value) -> untyped
end
