# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActiveModel::Attribute::FromUser < ::ActiveModel::Attribute
  def type_cast: (untyped value) -> untyped
  def came_from_user?: () -> untyped
end
