# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActionDispatch::Static
  def initialize: (untyped app, untyped path, ?index: ::String, ?headers: ::Hash[untyped, untyped]) -> void
  def call: (untyped env) -> untyped
end
