# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActiveStorage::Service::MirrorService < ::ActiveStorage::Service
  # Stitch together from named services.
  def self.build: (primary: untyped, mirrors: untyped, configurator: untyped, **untyped options) -> untyped
  def initialize: (primary: untyped, mirrors: untyped) -> void
  # Upload the +io+ to the +key+ specified to all services. If a +checksum+ is provided, all services will
  # ensure a match when the upload has completed or raise an ActiveStorage::IntegrityError.
  def upload: (untyped key, untyped io, ?checksum: untyped?, **untyped options) -> untyped
  # Delete the file at the +key+ on all services.
  def delete: (untyped key) -> untyped
  # Delete files at keys starting with the +prefix+ on all services.
  def delete_prefixed: (untyped prefix) -> untyped
  private def each_service: () ?{ () -> untyped } -> untyped
  private def perform_across_services: (untyped method, *untyped args) -> untyped
end
