# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActiveJob::ConfiguredJob
  def initialize: (untyped job_class, ?::Hash[untyped, untyped] options) -> void
  def perform_now: (*untyped args) -> untyped
  def perform_later: (*untyped args) -> untyped
end
