# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActiveStorage::Attached::Changes::CreateOneOfMany < ::ActiveStorage::Attached::Changes::CreateOne
  private def find_attachment: () -> untyped
end
