# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActionDispatch::Journey::Nodes::Cat < ::ActionDispatch::Journey::Nodes::Binary
  def cat?: () -> true
  def type: () -> :CAT
end
