# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActiveRecord::HasManyThroughCantAssociateThroughHasOneOrManyReflection < ::ActiveRecord::ThroughCantAssociateThroughHasOneOrManyReflection
end
