# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActiveRecord::HasManyThroughSourceAssociationNotFoundError < ::ActiveRecord::ActiveRecordError
  def initialize: (?untyped? reflection) -> void
end
