# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActiveRecord::MultiparameterAssignmentErrors < ::ActiveRecord::ActiveRecordError
  def initialize: (?untyped? errors) -> void
  attr_reader errors: untyped
end
