# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActiveRecord::PendingMigrationError < ::ActiveRecord::MigrationError
  def initialize: (?untyped? message) -> void
  include ActiveSupport::ActionableError
  extend ActiveSupport::ActionableError::ClassMethods
end
