# !!! GENERATED CODE !!!
# Please see generators/rails-generator

module ActiveRecord::TestFixtures
  def before_setup: () -> untyped
  def after_teardown: () -> untyped
  def run_in_transaction?: () -> untyped
  def setup_fixtures: (?untyped config) -> untyped
  def teardown_fixtures: () -> untyped
  def enlist_fixture_connections: () -> untyped
  # Shares the writing connection pool with connections on
  # other handlers.
  #
  # In an application with a primary and replica the test fixtures
  # need to share a connection pool so that the reading connection
  # can see data in the open transaction on the writing connection.
  private def setup_shared_connection_pool: () -> (nil | untyped)
  private def teardown_shared_connection_pool: () -> untyped
  private def load_fixtures: (untyped config) -> untyped
  private def instantiate_fixtures: () -> untyped
  private def load_instances?: () -> untyped
  extend ActiveSupport::Concern
end
