# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActiveRecord::UnknownPrimaryKey < ::ActiveRecord::ActiveRecordError
  def initialize: (?untyped? model, ?untyped? description) -> void
  attr_reader model: untyped
end
