# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActionDispatch::RequestId
  def initialize: (untyped app) -> void
  def call: (untyped env) -> untyped
  private def make_request_id: (untyped request_id) -> untyped
  private def internal_request_id: () -> untyped
  X_REQUEST_ID: String
end
