# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActionDispatch::ShowExceptions
  def initialize: (untyped app, untyped exceptions_app) -> void
  def call: (untyped env) -> untyped
  private def render_exception: (untyped request, untyped exception) -> untyped
  private def pass_response: (untyped status) -> ::Array[untyped | ::Hash[::String, ::String | "0"] | ::Array[untyped]]
  FAILSAFE_RESPONSE: Array[Integer | Hash[String, String] | Array[String]]
end
