# !!! GENERATED CODE !!!
# Please see generators/rails-generator

module ActionDispatch::Assertions
  def html_document: () -> untyped
  include ActionDispatch::Assertions::ResponseAssertions
  include ActionDispatch::Assertions::RoutingAssertions
  include Rails::Dom::Testing::Assertions
end
