# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActionDispatch::TestResponse < ::ActionDispatch::Response
  def self.from_response: (untyped response) -> untyped
  # Returns a parsed body depending on the response MIME type. When a parser
  # corresponding to the MIME type is not found, it returns the raw body.
  #
  # ==== Examples
  #   get "/posts"
  #   response.content_type      # => "text/html; charset=utf-8"
  #   response.parsed_body.class # => String
  #   response.parsed_body       # => "<!DOCTYPE html>\n<html>\n..."
  #
  #   get "/posts.json"
  #   response.content_type      # => "application/json; charset=utf-8"
  #   response.parsed_body.class # => Array
  #   response.parsed_body       # => [{"id"=>42, "title"=>"Title"},...
  #
  #   get "/posts/42.json"
  #   response.content_type      # => "application/json; charset=utf-8"
  #   response.parsed_body.class # => Hash
  #   response.parsed_body       # => {"id"=>42, "title"=>"Title"}
  def parsed_body: () -> untyped
  def response_parser: () -> untyped
end
