# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class ActiveSupport::Callbacks::CallTemplate::ProcCall
  def initialize: (untyped target) -> void
  def expand: (untyped target, untyped value, untyped block) -> ::Array[untyped | :call]
  def make_lambda: () -> untyped
  def inverted_lambda: () -> untyped
end
