# !!! GENERATED CODE !!!
# Please see generators/rails-generator

class Arel::UpdateManager < ::Arel::TreeManager
  def initialize: () -> void
  # #
  # UPDATE +table+
  def table: (untyped table) -> self
  def set: (untyped values) -> self
  include Arel::TreeManager::StatementMethods
end
